---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-agents-agentops-io-v1alpha1-agent
  failurePolicy: Fail
  name: vagent.kb.io
  rules:
  - apiGroups:
    - agents.agentops.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agents
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-agents-agentops-io-v1alpha1-agentresource
  failurePolicy: Fail
  name: vagentresource.kb.io
  rules:
  - apiGroups:
    - agents.agentops.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agentresources
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-agents-agentops-io-v1alpha1-agenttool
  failurePolicy: Fail
  name: vagenttool.kb.io
  rules:
  - apiGroups:
    - agents.agentops.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agenttools
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-agents-agentops-io-v1alpha1-channel
  failurePolicy: Fail
  name: vchannel.kb.io
  rules:
  - apiGroups:
    - agents.agentops.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - channels
  sideEffects: None
