/**
 * Operator Extension Config — loaded from /etc/operator/config.json.
 * Generated by the Kubernetes operator from the Agent CRD spec.
 */
export interface OperatorConfig {
  tools: ToolEntry[];
  mcpServers?: MCPEntry[];
  compaction?: CompactionEntry;
  providers: ProviderEntry[];
  primaryModel: string;
  primaryProvider: string;
  fallbackModels?: FallbackModelEntry[];
  toolHooks?: ToolHooksEntry;
  skills?: SkillEntry[];
  systemPrompt?: string;
  contextFiles?: ContextEntry[];
  builtinTools?: string[];
  thinkingLevel?: string;
}

export interface ToolEntry {
  name: string;
  path: string;
}

export interface MCPEntry {
  name: string;
  port: number;
  directTools?: string[];
}

export interface CompactionEntry {
  enabled: boolean;
  strategy: "auto" | "manual" | "off";
}

export interface ProviderEntry {
  name: string;
}

export interface FallbackModelEntry {
  provider: string;
  model: string;
}

export interface ToolHooksEntry {
  blockedCommands?: string[];
  allowedPaths?: string[];
  auditTools?: string[];
}

export interface SkillEntry {
  name: string;
  path: string;
}

export interface ContextEntry {
  path: string;
}

/**
 * Structured JSON output from task-mode agent runs.
 * Written to stdout for the operator to parse.
 */
export interface TaskResult {
  output: string;
  toolCalls: number;
  tokensUsed: number;
  cost: number;
  model: string;
  success: boolean;
  error?: string;
}

/**
 * Status response from daemon /status endpoint.
 */
export interface AgentStatus {
  busy: boolean;
  output?: string;
  toolCalls: number;
  tokensUsed: number;
  cost: string;
  model: string;
  sessionId?: string;
}

/**
 * Prompt request body for daemon /prompt endpoint.
 */
export interface PromptRequest {
  prompt: string;
}

/**
 * Steer request body for daemon /steer endpoint.
 */
export interface SteerRequest {
  message: string;
}

/**
 * Followup request body for daemon /followup endpoint.
 */
export interface FollowupRequest {
  prompt: string;
}
